trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    if [ $AGENT_OS == "Linux" ]; then
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
      echo "Started xvfb"
    fi
  displayName: Start xvfb

- bash: |
    yarn install
    yarn compile
    yarn test
  displayName: Run Tests
  env:
    DISPLAY: :10