on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install root project dependencies
        run: npm install
      - name: Install sample project dependencies
        run: npm install
        working-directory: ./sample
      - name: Compile sample project
        run: npm run compile
        working-directory: ./sample
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test --prefix ./sample
